name: Deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Docker Swarm
        env:
          MUSER: ${{ secrets.MUSER }}
          MHOST: ${{ secrets.MHOST }}
          CI_PROJECT_NAME: ${{ github.event.repository.name }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $MUSER@$MHOST << 'EOF'
            cd "$CI_PROJECT_NAME"

            docker service update --with-registry-auth --image "$CI_PROJECT_NAME:${{ github.ref_name }}" "app_$CI_PROJECT_NAME"

            if [ $? -eq 0 ]; then
              echo "✅ Deployment successful"
            else
              echo "❌ Deployment failed"
              exit 1
            fi

            docker buildx prune -f
            docker service ls
          EOF