name: Deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Docker Swarm
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.MUSER }}@${{ secrets.MHOST }} << EOF
            cd "${{ secrets.CI_PROJECT_NAME }}"

            docker service update --with-registry-auth --image "${{ secrets.CI_PROJECT_NAME }}:${GITHUB_REF##*/}" "app_${{ secrets.CI_PROJECT_NAME }}"

            docker buildx prune -f
            docker service ls
          EOF
