name: Migrate

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Run database migrations remotely
        env:
          MUSER: ${{ secrets.MUSER }}
          MHOST: ${{ secrets.MHOST }}
          CI_PROJECT_NAME: ${{ github.event.repository.name }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $MUSER@$MHOST << 'EOF'
            cd "$CI_PROJECT_NAME"

            echo "Running migrations with golang-migrate..."
            migrate \
              -path=./migrations \
              -database="postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?sslmode=disable" \
              up

            if [ \$? -eq 0 ]; then
              echo "✅ Migrations successful"
            else
              echo "❌ Migrations failed"
              exit 1
            fi
          EOF